### ISSUE TITLE
Add some docs for testing

### ISSUE THREAD

**Issue by garak** [mauretto78/in-memory-list#1]
I tried to clone repo, install vendors and run tests, but I'm getting a bunch of errors.
I guess that it depends on missing redis server, so I see the need for a few lines of instructions in README explaining how to test this library

**Comment by mauretto78** [comment]
Hi @garak and thank you for your feedback.

I added the "suggest" instruction in composer.json file:

    "suggest": {
        "ext-apcu": "*",
        "ext-memcached": "*",
        "ext-redis": "*"
    }

and finally I added some instructions to install all the drivers needed to run tests.

Hope this helps

M :)

**Comment by garak** [comment]
:+1:
